insert into public.learning_courses (
  category_id,
  slug,
  title_en,
  title_ar,
  subtitle_en,
  subtitle_ar,
  summary_en,
  summary_ar,
  level,
  duration,
  language,
  price_omr,
  is_published,
  sort_order
)
select
  course_categories.id,
  course_data.slug,
  course_data.title_en,
  course_data.title_ar,
  course_data.subtitle_en,
  course_data.subtitle_ar,
  course_data.summary_en,
  course_data.summary_ar,
  course_data.level,
  course_data.duration,
  course_data.language,
  course_data.price_omr,
  true,
  course_data.sort_order
from public.course_categories
join (
  values
    (
      'software-engineering',
      'frontend-engineering-for-omani-graduates',
      'Frontend Engineering For Omani Graduates',
      'Frontend Engineering For Omani Graduates',
      'Build modern web interfaces with HTML, CSS, JavaScript, React, and portfolio projects.',
      'Build modern web interfaces with HTML, CSS, JavaScript, React, and portfolio projects.',
      'A practical frontend path for graduates who need stronger web development skills before applying for junior software roles.',
      'A practical frontend path for graduates who need stronger web development skills before applying for junior software roles.',
      'Beginner to Intermediate',
      '8 weeks',
      'English + Arabic support',
      29.000,
      10
    ),
    (
      'software-engineering',
      'backend-api-development-with-database',
      'Backend API Development With Database',
      'Backend API Development With Database',
      'Learn databases, authentication, storage, and API workflows using a practical backend stack.',
      'Learn databases, authentication, storage, and API workflows using a practical backend stack.',
      'A backend course focused on the skills junior developers need when working with application data, users, and secure access.',
      'A backend course focused on the skills junior developers need when working with application data, users, and secure access.',
      'Intermediate',
      '7 weeks',
      'English',
      35.000,
      20
    ),
    (
      'artificial-intelligence',
      'applied-ai-for-business-and-productivity',
      'Applied AI For Business And Productivity',
      'Applied AI For Business And Productivity',
      'Use AI tools, prompt workflows, and automation to solve practical workplace problems.',
      'Use AI tools, prompt workflows, and automation to solve practical workplace problems.',
      'A practical AI course for graduates who need to understand modern AI tools and use them responsibly in business contexts.',
      'A practical AI course for graduates who need to understand modern AI tools and use them responsibly in business contexts.',
      'Beginner',
      '5 weeks',
      'English + Arabic support',
      25.000,
      30
    ),
    (
      'cyber-security',
      'cyber-security-foundations-for-junior-roles',
      'Cyber Security Foundations For Junior Roles',
      'Cyber Security Foundations For Junior Roles',
      'Learn security concepts, common threats, access control, and safe operational practices.',
      'Learn security concepts, common threats, access control, and safe operational practices.',
      'A foundation course for graduates preparing for entry-level security, support, or IT operations roles.',
      'A foundation course for graduates preparing for entry-level security, support, or IT operations roles.',
      'Beginner',
      '6 weeks',
      'English',
      30.000,
      40
    ),
    (
      'data-analytics',
      'data-analytics-with-excel-sql-and-dashboards',
      'Data Analytics With Excel, SQL, And Dashboards',
      'Data Analytics With Excel, SQL, And Dashboards',
      'Turn raw data into clear reports using spreadsheet analysis, SQL queries, and dashboard thinking.',
      'Turn raw data into clear reports using spreadsheet analysis, SQL queries, and dashboard thinking.',
      'A job-focused analytics path for graduates who want practical reporting and business insight skills.',
      'A job-focused analytics path for graduates who want practical reporting and business insight skills.',
      'Beginner to Intermediate',
      '7 weeks',
      'English + Arabic support',
      32.000,
      50
    ),
    (
      'career-readiness',
      'graduate-tech-job-readiness',
      'Graduate Tech Job Readiness',
      'Graduate Tech Job Readiness',
      'Prepare a stronger CV, portfolio, LinkedIn profile, interview answers, and job search workflow.',
      'Prepare a stronger CV, portfolio, LinkedIn profile, interview answers, and job search workflow.',
      'A practical employability course for graduates who need to present their skills clearly to technology employers in Oman.',
      'A practical employability course for graduates who need to present their skills clearly to technology employers in Oman.',
      'Beginner',
      '4 weeks',
      'English + Arabic support',
      18.000,
      60
    )
) as course_data (
  category_slug,
  slug,
  title_en,
  title_ar,
  subtitle_en,
  subtitle_ar,
  summary_en,
  summary_ar,
  level,
  duration,
  language,
  price_omr,
  sort_order
)
  on course_categories.slug = course_data.category_slug
on conflict (slug) do update
set
  category_id = excluded.category_id,
  title_en = excluded.title_en,
  title_ar = excluded.title_ar,
  subtitle_en = excluded.subtitle_en,
  subtitle_ar = excluded.subtitle_ar,
  summary_en = excluded.summary_en,
  summary_ar = excluded.summary_ar,
  level = excluded.level,
  duration = excluded.duration,
  language = excluded.language,
  price_omr = excluded.price_omr,
  is_published = excluded.is_published,
  sort_order = excluded.sort_order,
  updated_at = now();
