
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  institute text,
  subject text not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending', 'reviewed', 'scheduled', 'completed', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists contact_messages_status_idx
  on public.contact_messages (status);

create index if not exists contact_messages_created_at_idx
  on public.contact_messages (created_at desc);

create index if not exists contact_messages_status_created_at_idx
  on public.contact_messages (status, created_at desc);

alter table public.contact_messages enable row level security;

drop policy if exists "Anyone can insert contact messages" on public.contact_messages;
create policy "Anyone can insert contact messages"
on public.contact_messages
for insert
with check (true);

drop policy if exists "Authenticated users can read their own contact messages" on public.contact_messages;
create policy "Authenticated users can read their own contact messages"
on public.contact_messages
for select
using (auth.role() = 'authenticated');
